package: s3fs
user: s3fs

platform:
  - linux-64
  - osx-64
  - win-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5

install:
  - conda config --add channels dask

before_script:
  - conda info
  - python -V

script:
  - conda build conda.recipe

build_targets: conda

iotimeout: 600
